config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticate :user do
    get 'reservations/template', to: 'reservations#template', as: 'reservation_template'
    resources :reservations
    root 'reservations#index'
    resources :time_slots
    resources :hotels
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/time_slot.rb
class TimeSlot < ApplicationRecord
    has_many :reservations
    validates :start_time, presence: { message: "Please select start time." }
    validates :end_time, presence: { message: "Please select end time." }

    def formatted_time_slot
        if start_time.present? && end_time.present?
          "#{start_time.strftime('%I:%M %p')} - #{end_time.strftime('%I:%M %p')}"
        else
          "Unknown Timeslot"
        end
    end

    def self.ransackable_attributes(auth_object = nil)
      ["created_at", "id", "start_time", "end_time", "updated_at"]
   end

   def self.ransackable_associations(auth_object = nil)
      ["reservations"]
  end
end

app/controllers/time_slots_controller.rb
class TimeSlotsController < ApplicationController
  before_action :set_time_slot, only: %i[ show edit update destroy ]

  # GET /time_slots or /time_slots.json
  def index
    @q = TimeSlot.ransack(params[:q])
    @pagy, @time_slots = pagy(@q.result(distinct: true).order(created_at: :asc), items: 10)
  end

  # GET /time_slots/1 or /time_slots/1.json
  def show
  end

  # GET /time_slots/new
  def new
    @time_slot = TimeSlot.new
  end

  # GET /time_slots/1/edit
  def edit
  end

  # POST /time_slots or /time_slots.json
  def create
    @time_slot = TimeSlot.new(time_slot_params)

    respond_to do |format|
      if @time_slot.save
        format.html { redirect_to time_slot_url(@time_slot), notice: "Time slot was successfully created." }
        format.json { render :show, status: :created, location: @time_slot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_slots/1 or /time_slots/1.json
  def update
    respond_to do |format|
      if @time_slot.update(time_slot_params)
        format.html { redirect_to time_slot_url(@time_slot), notice: "Time slot was successfully updated." }
        format.json { render :show, status: :ok, location: @time_slot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @time_slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_slots/1 or /time_slots/1.json
  def destroy
    @time_slot.destroy!

    respond_to do |format|
      format.html { redirect_to time_slots_url, notice: "Time slot was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_slot
      @time_slot = TimeSlot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def time_slot_params
      params.require(:time_slot).permit(:start_time, :end_time)
    end
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/views/time_slots/_form.html.erb
<%= form_with(model: time_slot) do |form| %>
  <% if time_slot.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(time_slot.errors.count, "error") %> prohibited this time_slot from being saved:</h2>

      <ul>
        <% time_slot.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :start_time, style: "display: block" %>
    <%= form.time_field :start_time, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :end_time, style: "display: block" %>
    <%= form.time_field :end_time, class: 'form-control' %>
  </div>

  <div class="row">
    <div class="col">
      <%= form.submit class: 'btn btn-primary mt-3' %>
      <%= link_to "Back to Time slots", time_slots_path, class: "btn btn-secondary mt-3" %>
    </div>
  </div>

<% end %>

app/views/time_slots/_time_slot.html.erb
<%= turbo_frame_tag :results do %>
  <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover"">
      <tbody>
        <tr id="<%= dom_id time_slot %>">
          <td><strong>Start time:</strong></td>
          <td><%= time_slot.start_time %></td>
        </tr>
        <tr>
          <td><strong>End time:</strong></td>
          <td><%= time_slot.end_time %></td>
        </tr>
      </tbody>
    </table>
  </div>
<% end %>

app/views/time_slots/edit.html.erb
<h1>Editing time slot</h1>

<%= render "form", time_slot: @time_slot %>

<br>

<div>
  <%= link_to "Show this time slot", @time_slot %> |
  <%= link_to "Back to time slots", time_slots_path %>
</div>

app/views/time_slots/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>
  
  <div class="row">
    <div class="col-md-9">
      <h1>Hotel Reservation system</h1>
    </div>
    <div class="col-md-3 offset">
      <% if user_signed_in? %>
        <%= button_to "Sign out", destroy_user_session_path, method: 'delete', data: { turbo: "false" }, class: "btn btn-danger" %>
        <%= Time.zone.now %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col">
    <%= link_to "Add Time slot", new_time_slot_path, class: 'btn btn-primary add-btn' %>
    <%= link_to 'Reservations', reservations_path, class: 'btn btn-primary add-btn' %>
    <%= link_to 'Hotel', hotels_path, class: 'btn btn-primary add-btn' %>
    <br>
    </div>
  </div>

  <div class="container pt-3">

  <%= search_form_for @q, data: { turbo_frame: "results", turbo_action: "advance", controller: "form", action: "input->form#submit" } do |f| %>
      <div class="row">
        <div class="col">
          <%= f.search_field :start_time_or_end_time_cont, class: 'search-input', placeholder: "search" %>
        </div>
      </div>
  <% end %>
  <%= turbo_frame_tag :results, data: {turbo_action: "advance"} do %>
    <%= Time.zone.now %>
    <% if @time_slots.empty? %>
      <h1>No Time slots found</h1>
    <% else %>
      <div class="div">
        <div class="row">
          <div class="col-md-9">
            <h2 class="mt-1 mb-3">Time Slot List</h2>
          </div>
        </div>
        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover" id="reservation-table" border="0"">
            <thead>
              <tr>
                <th><%= sort_link(@q, :id, default_order: :desc) %></th>
                <th><%= sort_link(@q, :start_time, default_order: :desc) %></th>
                <th><%= sort_link(@q, :end_time, default_order: :desc) %></th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody id="time_slots">
              <% @time_slots.each do |time_slot| %>
                <tr>
                <td><%= time_slot.id %></td>
                <td><%= link_to time_slot.start_time, time_slot, data: {turbo_frame: "_top"} %></td>
                <td><%= link_to time_slot.end_time, time_slot, data: {turbo_frame: "_top"} %></td>
                  <td>
                  <%= link_to 'Edit', edit_time_slot_path(time_slot), class: 'btn btn-secondary edit-btn', data: {turbo_frame: "_top"} %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="pagy-container">
            <%== pagy_nav(@pagy) %>
        </div>
      </div>
    <% end %>
  <% end %>
  </div>
</div>

app/views/time_slots/new.html.erb
<div class="container form-control">
<h1>New time slot</h1>

<%= render "form", time_slot: @time_slot %>

<br>
</div>

app/views/time_slots/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <%= render @time_slot %>

  
  <div class="row mt-4">
    <div class="col">
    <%= link_to "Edit this time slot", edit_time_slot_path(@time_slot), class: "btn btn-primary" %> 
    <%= link_to "Back to time slots", time_slots_path, class: "btn btn-primary"%> 
    <%= button_to "Destroy this time slot", @time_slot, method: :delete, class: "btn btn-danger" %>
    </br>
    </div>
  </div>
</div>