config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticate :user do
    get 'reservations/template', to: 'reservations#template', as: 'reservation_template'
    resources :reservations
    root 'reservations#index'
    resources :time_slots
    resources :hotels
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :user
    belongs_to :time_slot
    belongs_to :hotel

    validates :customer_name, uniqueness: true, presence: { message: "Please provide a customer name." }
    #validates :customer_phone, uniqueness: true, presence: { message: "Please provide a customer phone." }
    validates :customer_email, uniqueness: true, presence: { message: "Please provide a customer email." }
    validates :persons_size, presence: { message: "Please provide number of persons." }
    validates :reservation_date, presence: { message: "please select reservation day." }
    accepts_nested_attributes_for :hotel, reject_if: :all_blank, allow_destroy: true
    accepts_nested_attributes_for :time_slot, reject_if: :all_blank, allow_destroy: true
    after_create :send_whatsapp_notification


    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "customer_email", "customer_name", "customer_phone", "hotel_id", "id", "persons_size", "reservation_date", "time_slot_id", "updated_at", "user_id"]
    end
    def self.ransackable_associations(auth_object = nil)
        ["hotel", "time_slot", "user"]
    end


    def send_whatsapp_notification
        message_body = "Your reservation for #{hotel.name} on #{reservation_date} at #{time_slot.formatted_time_slot} has been successfully created. Thank you!"
        TwilioService.new.send_whatsapp_message(self.customer_phone, message_body)
    end
    
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show edit update destroy ]

  # GET /reservations or /reservations.json
  def index
    # @reservations = Reservation.all
    @q = Reservation.ransack(params[:q])
    @pagy, @reservations = pagy(@q.result.includes(:hotel, :time_slot).order(created_at: :asc), items: 10)
    
  end

  # GET /reservations/1 or /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations or /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.user_id = current_user.id

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to reservation_url(@reservation), notice: "Reservation was successfully created." }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to reservation_url(@reservation), notice: "Reservation was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation.destroy!

    respond_to do |format|
      format.html { redirect_to reservations_url, notice: "Reservation was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  def template
    @name = "John Doe"
    @event = "Event Name"
    @date = Date.today.strftime("%B %d, %Y")
    @logo_url = "path/to/your/logo.png"  # Replace with the actual path or URL of your logo
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:customer_name, :customer_email, :customer_phone, :persons_size, :reservation_date, :user_id, :hotel_id, :time_slot_id )
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_with(model: reservation) do |form| %>
  <% if reservation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :customer_name, style: "display: block"  %>
    <%= form.text_field :customer_name, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :customer_email, style: "display: block" %>
    <%= form.text_field :customer_email, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :customer_phone, style: "display: block" %>
    <%= form.text_field :customer_phone, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :persons_size, style: "display: block" %>
    <%= form.text_field :persons_size, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :Hotel, style: "display: block" %>
    <%= form.collection_select :hotel_id, Hotel.all, :id, :name, { prompt: 'Select Hotel' }, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :reservation_date, style: "display: block" %>
    <%= form.date_field :reservation_date, class: 'form-control' %>
  </div>

  <div>
    <%= form.label :time_slot, style: "display: block" %>
    <%= form.collection_select :time_slot_id, TimeSlot.all, :id, :formatted_time_slot, { prompt: 'Select Timeslot' }, class: 'form-control' %>
  </div>

  <div>
    <%= form.submit  class: 'btn btn-primary mt-3' %>
  </div>
<% end %>

app/views/reservations/_reservation.html.erb
<%= turbo_frame_tag :results do %>
  <div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <tbody>
      <tr id="<%= dom_id reservation %>">
        <td><strong>Customer name:</strong></td>
        <td><%= reservation.customer_name %></td>
      </tr>
      <tr>
        <td><strong>Customer email:</strong></td>
        <td><%= reservation.customer_email %></td>
      </tr>
      <tr>
        <td><strong>Customer phone:</strong></td>
        <td><%= reservation.customer_phone %></td>
      </tr>
      <tr>
        <td><strong>Persons size:</strong></td>
        <td><%= reservation.persons_size %></td>
      </tr>
      <tr>
        <td><strong>Reservation date:</strong></td>
        <td><%= reservation.reservation_date %></td>
      </tr>
    </tbody>
  </table>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<div class="container">
<h1>Editing reservation</h1>
  <%= render "form", reservation: @reservation %>

<br>

<div>
  <%= link_to "Show this reservation", @reservation, class: "btn btn-primary" %> 
  <%= link_to "Back to reservations", reservations_path, class: "btn btn-secondary" %>
</div>
</div>

app/views/reservations/index.html.erb
<!--<nav class="navbar navbar-expand-lg bg-body-tertiary">
<div class="container-fluid">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="#">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Dropdown
        </a>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="#">Action</a></li>
          <li><a class="dropdown-item" href="#">Another action</a></li>
          <li><hr class="dropdown-divider"></li>
          <li><a class="dropdown-item" href="#">Something else here</a></li>
        </ul>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="d-flex" role="search">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</div>
</nav> -->
<div class="container">
  <div class="row">
    <div class="col-md-9">
      <h1>Hotel Reservation system</h1>
    </div>
    <div class="col-md-3 offset">
      <% if user_signed_in? %>
        <%= button_to "Sign out", destroy_user_session_path, method: 'delete', data: { turbo: "false" }, class: "btn btn-danger" %>
        <%= Time.zone.now %>
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col">
    <%= link_to "Add Reservation", new_reservation_path, class: 'btn btn-primary add-btn' %>
    <%= link_to 'Hotels', hotels_path, class: 'btn btn-primary add-btn' %>
    <%= link_to 'Time slots', time_slots_path, class: 'btn btn-primary add-btn' %>
    <br>
    </div>
  </div>

  <div class="container pt-3">
    
    <%= search_form_for @q, data: { turbo_frame: "results", turbo_action: "advance", controller: "form", action: "input->form#submit" } do |f| %>
      <div class="row">
        <div class="col">
          <div class="search-row">
          <%= f.label :customer_name_cont, "Search Name", class: "search-label" %>
          <%= f.search_field :customer_name_or_customer_email_or_customer_phone_or_hotel_name_cont, class: 'search-input', placeholder: "search" %>
        </div>
        </div>
      </div>
    <% end %>

    <%= turbo_frame_tag :results, data: {turbo_action: "advance"} do %>
      <%= Time.zone.now %>
      <% if @reservations.empty? %>
        <h1>No reservations found</h1>
      <% else %>
        <div class="div reservation-table">
          <div class="row">
            <div class="col-md-9">
              <h2 class="mt-1 mb-3">Reservation List</h2>
            </div>
          </div>
          <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover reservation-table" id="reservation-table" data-controller="reservation" border="0">
              <thead>
                <tr>
                  <th><%= sort_link(@q, :id, default_order: :desc) %></th>
                  <th><%= sort_link(@q, :customer_name, default_order: :desc) %></th>
                  <th><%= sort_link(@q, :customer_phone, default_order: :desc) %></th>
                  <th><%= sort_link(@q, :customer_email, default_order: :desc) %></th>
                  <th><%= sort_link(@q, :hotel_name) %></th>
                  <th><%= sort_link(@q, :reservation_date, default_order: :desc) %></th>
                  <th><%= sort_link(@q, :time_slot_start_time, default_order: :desc) %></th>
                  <th><%= sort_link(@q, :time_slot_end_time, default_order: :desc) %></th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                <% @reservations.each do |reservation| %>
                  <tr>
                    <td><%= reservation.id %></td>
                    <td><%= link_to reservation.customer_name, reservation, data: {turbo_frame: "_top"} %></td>
                    <td><%= reservation.customer_phone %></td>
                    <td><%= reservation.customer_email %></td>
                    <td><%= reservation.hotel.name %></td>
                    <td><%= reservation.reservation_date %></td>
                    <td><%= reservation.time_slot.start_time.strftime('%I:%M %p') %></td>
                    <td><%= reservation.time_slot.end_time.strftime('%I:%M %p') %></td>
                    <td>
                      <%= link_to 'Edit', edit_reservation_path(reservation), class: 'btn btn-secondary edit-btn', data: {turbo_frame: "_top"} %>
                      <br>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <div class="pagy-container">
            <%== pagy_nav(@pagy) %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/reservations/new.html.erb
<div class="container form-control">
<h1>New reservation</h1>

<%= render "form", reservation: @reservation %>

<br>

<div>
  <%= link_to "Back to reservations", reservations_path, class: "btn btn-secondary" %>
</div>
</div>

app/views/reservations/show.html.erb
<div class="container"
<p style="color: green"><%= notice %></p>

<%= render @reservation %>

  <div class="row mt-4">
    <div class="col">
    <%= link_to "Edit", edit_reservation_path(@reservation), class: "btn btn-primary" %> 
    <%= link_to "Back to reservations", reservations_path, class: "btn btn-primary"%> 
    <%= button_to "Destroy", @reservation, method: :delete, class: "btn btn-danger" %>
    </br>
    </div>
  </div>
</div>

app/views/reservations/template.html.erb
<!-- app/views/reservations/template.html.erb -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Reservation Confirmation</title>
</head>
<body>
  <div class="container text-center">
    <img src="<%= @logo_url %>" alt="Logo" class="logo">
    <hr style="border: none; height: 2px; background-color: black; margin-bottom: 20px;">
    <div class="row">
    <div class="details h3">Hi iqtadar!</div>
      <div class="message">Your request for table reservation has been approved</div>
    </div>
    <hr style="border: none; height: 2px; background-color: black; margin-top: 30px;">
    <div class="row">
      <div class="col-md-6">
      <div class="message">Hello <%= @name %>,</div>
      <div>Phone No: 03214834100</div>
      <div>Reservation Date: hardcoded date</div>
      <div>Time Frame: Lunch</div>
      </div>
      <br>
      <div class="col-md-6">
      <div class="message">email: iqtadar.hassn...@.com,</div>
      <div>Phone No: 03214834100</div>
      <div>Reservation Date: hardcoded date</div>
      <div>Time Frame: 6:00 - 9:00</div>
      </div>
    </div>
  </div>
</body>
</html>