config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticate :user do
    get 'reservations/template', to: 'reservations#template', as: 'reservation_template'
    resources :reservations
    root 'reservations#index'
    resources :time_slots
    resources :hotels
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/hotel.rb
class Hotel < ApplicationRecord
   has_many :reservations
   validates :name, uniqueness: true, presence: { message: "Please provide a hotel name." }

   def self.ransackable_attributes(auth_object = nil)
      ["created_at", "id", "name", "updated_at"]
   end

   def self.ransackable_associations(auth_object = nil)
      ["reservations"]
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: %i[ show edit update destroy ]

  # GET /hotels or /hotels.json
  def index
    @q = Hotel.ransack(params[:q])
    @pagy, @hotels = pagy(@q.result(distinct: true).order(created_at: :asc), items: 10)
  end

  # GET /hotels/1 or /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels or /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to hotel_url(@hotel), notice: "Hotel was successfully created." }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1 or /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to hotel_url(@hotel), notice: "Hotel was successfully updated." }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1 or /hotels/1.json
  def destroy
    @hotel.destroy!

    respond_to do |format|
      format.html { redirect_to hotels_url, notice: "Hotel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hotel_params
      params.require(:hotel).permit(:name)
    end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.erb
<%= form_with(model: hotel) do |form| %>
  <% if hotel.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
        <% hotel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :customer_name, style: "display: block"  %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="row">
    <div class="col">
      <%= form.submit  class: 'btn btn-primary mt-3' %>
      <%= link_to "Back to reservations", reservations_path, class: "btn btn-secondary mt-3" %>
    </div>
  </div>
<% end %>

app/views/hotels/_hotel.html.erb
<%= turbo_frame_tag :results do %>
  <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover"">
      <tbody>
        <tr id="<%= dom_id hotel %>">
          <td><strong>Hotel name:</strong></td>
          <td><%= hotel.name %></td>
        </tr>
        <tr>
          <td><strong>Created on:</strong></td>
          <td><%= hotel.created_at %></td>
        </tr>
      </tbody>
    </table>
  </div>
<% end %>

app/views/hotels/edit.html.erb
<div class="container">
<h1>Editing hotel</h1>

<%= render "form", hotel: @hotel %>

<br>

<div>
  <%= link_to "Show this hotel", @hotel %> |
  <%= link_to "Back to hotels", hotels_path %>
</div>
</div>

app/views/hotels/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>
  
  <div class="row">
    <div class="col-md-9">
      <h1>Hotel Reservation system</h1>
    </div>
    <div class="col-md-3 offset">
      <% if user_signed_in? %>
        <%= button_to "Sign out", destroy_user_session_path, method: 'delete', data: { turbo: "false" }, class: "btn btn-danger" %>
        <%= Time.zone.now %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col">
    <%= link_to "Add Hotel", new_hotel_path, class: 'btn btn-primary add-btn' %>
    <%= link_to 'Reservations', reservations_path, class: 'btn btn-primary add-btn' %>
    <%= link_to 'Time slots', time_slots_path, class: 'btn btn-primary add-btn' %>
    <br>
    </div>
  </div>

  <div class="container pt-3">

  <%= search_form_for @q, data: { turbo_frame: "results", turbo_action: "advance", controller: "form", action: "input->form#submit" } do |f| %>
      <div class="row">
        <div class="col">
          <%= f.search_field :name_cont, class: 'search-input', placeholder: "search" %>
        </div>
      </div>
  <% end %>
  <%= turbo_frame_tag :results, data: {turbo_action: "advance"} do %>
    <%= Time.zone.now %>
    <% if @hotels.empty? %>
      <h1>No hotels found</h1>
    <% else %>
      <div class="div reservation-table">
        <div class="row">
          <div class="col-md-9">
            <h2 class="mt-1 mb-3">Hotel List</h2>
          </div>
        </div>
        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover" id="reservation-table" data-controller="reservation" border="0"">
            <thead>
              <tr>
                <th><%= sort_link(@q, :id, default_order: :desc) %></th>
                <th><%= sort_link(@q, :name, default_order: :desc) %></th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody id="hotels">
              <% @hotels.each do |hotel| %>
                <tr>
                <td><%= hotel.id %></td>
                <td><%= link_to hotel.name, hotel, data: {turbo_frame: "_top"} %></td>
                  <td>
                  <%= link_to 'Edit', edit_hotel_path(hotel), class: 'btn btn-secondary edit-btn', data: {turbo_frame: "_top"} %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="pagy-container">
            <%== pagy_nav(@pagy) %>
        </div>
      </div>
    <% end %>
  <% end %>
  </div>
</div>

app/views/hotels/new.html.erb
<div class="container form-control">
  <h1>New hotel</h1>

  <%= render "form", hotel: @hotel %>

  <br>

  
</div>

app/views/hotels/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <%= render @hotel %>

  
  <div class="row mt-4">
    <div class="col">
    <%= link_to "Edit", edit_hotel_path(@hotel), class: "btn btn-primary" %> 
    <%= link_to "Back to hotels", hotels_path, class: "btn btn-primary"%> 
    <%= button_to "Destroy", @hotel, method: :delete, class: "btn btn-danger" %>
    </br>
    </div>
  </div>
</div>